apache/uima-uimaj

.gitignore

- Ignore files that should not go into the repo
https://issues.apache.org/jira/browse/UIMA-6126

[UIMA-6126] Add .gitignore file to trunk

---

uimaj-core/src/main/java/org/apache/uima/cas/impl/FSIndexComparatorImpl.java
uimaj-core/src/main/java/org/apache/uima/cas/impl/LinearTypeOrderBuilderImpl.java
uimaj-core/src/test/java/org/apache/uima/analysis_engine/impl/AnalysisEngine_implTest.java

please see if this fixes the performance issue

[UIMA-6136] fix hashcode and equals for FsIndexComparatorImpl

---

uima-docbook-references/src/docbook/ref.pear.xml
uima-docbook-references/src/docbook/ref.xml.component_descriptor.xml
uimaj-core/src/main/java/org/apache/uima/analysis_engine/impl/PearAnalysisEngineWrapper.java
uimaj-core/src/main/java/org/apache/uima/resource/PearSpecifier.java
uimaj-core/src/main/java/org/apache/uima/resource/impl/PearSpecifier_impl.java
uimaj-core/src/main/resources/resourceSpecifierSchema.xsd
uimaj-core/src/test/java/org/apache/uima/analysis_engine/impl/PearAnalysisEngineWrapperTest.java
uimaj-core/src/test/java/org/apache/uima/resource/impl/PearSpecifier_implTest.java
uimaj-core/src/test/java/org/apache/uima/util/impl/XMLParser_implTest.java
uimaj-core/src/test/resources/XmlParserTest/TestPearSpecifier.xml

Bring master up-to-date with changes in master-v2. This includes primarily the changes for [UIMA-5936] as other changse have already been cherry-picked/merged otherwise
Once this is merged, future changes to the v2 branch can be merged into v3 by merging again the master-v2 branch into the master branch.
Jira: https://issues.apache.org/jira/browse/UIMA-5936

Master merge v2

---

uimaj-core/src/main/java/org/apache/uima/cas/SerialFormat.java
uimaj-core/src/main/java/org/apache/uima/cas/impl/XCASSerializer.java
uimaj-core/src/main/java/org/apache/uima/cas/impl/XmiCasSerializer.java
uimaj-core/src/main/java/org/apache/uima/util/CasIOUtils.java
uimaj-core/src/test/java/org/apache/uima/cas/impl/XmiCasSerializerTest.java

support serializing using xml 1.1 for xmi and xcas

[UIMA-6128] add XMI_1_1 and XCAS_1_1 as SerialFormat entries, and

---

uimaj-core/src/main/java/org/apache/uima/util/CasIOUtils.java

add missing support for xcas 1.1 serial format

[UIMA-6128] hook up xcas-1-1 to save

---

uimaj-core/src/main/java/org/apache/uima/cas/impl/BinaryCasSerDes.java
uimaj-core/src/main/java/org/apache/uima/cas/impl/CASImpl.java
uimaj-core/src/test/java/org/apache/uima/cas/test/SerializationReinitTest.java
uimaj-core/src/test/java/org/apache/uima/util/CasIOUtilsAlwaysHoldOnTest.java
uimaj-core/src/test/java/org/apache/uima/util/CasIOUtilsTest.java

JIRA Issue: https://issues.apache.org/jira/browse/UIMA-6199
- Added a unit test demonstrating the issue (currently failing of course)

[UIMA-6199] Unindexed document annotation added back to index during deserialization

---

uimaj-core/pom.xml
uimaj-core/src/main/java/org/apache/uima/flow/impl/CapabilityLanguageFlowController.java
uimaj-core/src/main/java/org/apache/uima/flow/impl/FixedFlowController.java
uimaj-core/src/main/java/org/apache/uima/util/CasIOUtils.java
uimaj-core/src/main/resources/org/apache/uima/flow/CapabilityLanguageFlowController.xml
uimaj-core/src/test/java/org/apache/uima/flow/impl/CapabilityLanguageFlowControllerTest.java
uimaj-core/src/test/java/org/apache/uima/flow/impl/FixedFlowControllerTest.java
uimaj-core/src/test/resources/CapabilityLanguageFlowControllerTest/CapabilityLanguageFlowController.xml
uimaj-core/src/test/resources/FixedFlowControllerTest/FixedFlowController.xml
uimaj-parent/pom.xml

* [UIMA-6200] Constructing aggregate engines is slow
* [UIMA-6187] add eol=lf for .sh files
* [UIMA-6128] hook up xcas-1-1 to save

Sync master v2 to master

---

.gitignore
uima-docbook-overview-and-setup/pom.xml
uima-docbook-references/pom.xml
uima-docbook-tools/pom.xml
uima-docbook-tutorials-and-users-guides/pom.xml

- Exclude issuesFixed folder from repo
- Add ASF SNAPSHOT repo declaration to the docbook modules because the DocBook build process does not work with them...

[NO JIRA] Exclude issues fixed folder from repo and fix Docbook build again

---

Jenkinsfile
uimaj-parent/pom.xml

- Added Jenkinsfile from master branch here as well
- Tell the rat to log the names of files with bad license headers to the console since on ci-builds, we do not seem to have access to browse workspaces
- Formatting

[UIMA-6259] Jenkinsfile for UIMA Java SDK

---

uimaj-core/pom.xml
uimaj-core/src/main/java/org/apache/uima/jcas/impl/JCasImpl.java
uimaj-core/src/test/java/org/apache/uima/cas/test/JCasClassLoaderTest.java

- Implemented unit test which demonstrates the issue
Jira issue: https://issues.apache.org/jira/browse/UIMA-6243

[UIMA-6243] JCas returns Annotation when asked for a specific subtype

---

Jenkinsfile

... there seems to be a problem with the "nohup" command not being found - no idea why

[NO JIRA] Do not build on ASF Windows nodes

---

uimaj-core/pom.xml

- Exclude new test files from rat check

[UIMA-6273] isBeforeV3 variable not reset in BinaryCasSerDes

---

uimaj-core/src/main/java/org/apache/uima/cas/impl/Subiterator.java
uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsTest.java

- Respect bounds when skipping over the bounding annotation
https://issues.apache.org/jira/browse/UIMA-6282

[UIMA-6282] select.at() may fail to respect bounds

---

uimaj-core/src/test/java/org/apache/uima/cas/test/AnnotationIteratorTest.java

- Do not spam the console with feature structures

[UIMA-6290] Clean up AnnotationIteratorTest

---

Jenkinsfile
pom.xml
uimaj-parent/pom.xml

... because it triggers on debug code in an Eclipse plugin that I do not want to refactor right now

[No Jira] Disable spotbugs

---

uimaj-core/src/test/java/org/apache/uima/analysis_engine/impl/AnalysisEngineDescription_implTest.java
uimaj-core/src/test/java/org/apache/uima/resource/metadata/impl/MetaDataObject_implTest.java
uimaj-core/src/test/java/org/apache/uima/resource/metadata/impl/TypeSystemDescription_implTest.java
uimaj-test-util/src/main/java/org/apache/uima/test/junit_extension/PrintExceptionsWhenRunFromCommandLineRule.java

- Upgraded MetaDataObject_implTest
- Upgraded TypeSystemDescription_implTest
- Upgrade AnalysisEngineDescription_impltTest
- Added PrintExceptionsWhenRunFromCommandLineRule as a replacement for JUnitExtension.handleException(e) in try/catch around tests

[UIMA-6308] Refactor unit tests

---

uimaj-core/src/main/java/org/apache/uima/analysis_engine/impl/AnalysisEngineDescription_impl.java
uimaj-core/src/main/java/org/apache/uima/internal/util/MetaDataObjectUtils.java
uimaj-core/src/test/java/org/apache/uima/analysis_engine/impl/AnalysisEngineDescription_implTest.java
uimaj-core/src/test/java/org/apache/uima/analysis_engine/impl/metadata/MetaDataObjectAssert.java
uimaj-core/src/test/java/org/apache/uima/cas/test/JCasClassLoaderTest.java

- Added test to check if clone() changes the imports in an AnalysisEngineDescription instance and whether the cloned instance has the same imports (unresolved) as the original

[UIMA-6300] deep copy feature for org.apache.uima.analysis_engine.AnalysisEngineDescription class

---

uimaj-core/src/main/java/org/apache/uima/util/impl/Slf4jLogger_impl.java

- Demote log level of CONFIG from info to debug - retain marker

[UIMA-6303] Logs are spammed with "Import by location/name" messages

---

uimaj-eclipse-update-site/.gitignore
uimaj-eclipse-update-site/pom.xml

- Remove the Pack200 stuff
- Formatting

[UIMA-6316] Stop using the deprecated pack200 when building update sites

---

uimaj-core/src/test/java/org/apache/uima/cas/test/JCasClassLoaderTest.java

[UIMA-6310] JCasClassLoaderTest sometimes fails

---

uimaj-core/src/main/java/org/apache/uima/cas/SerialFormat.java
uimaj-core/src/main/java/org/apache/uima/util/CasIOUtils.java

- Added XMI_PRETTY and XMI_1_1_PRETTY

[UIMA-6203] Add SerialFormat.XMI_PRETTY

---

uimaj-core/src/main/java/org/apache/uima/cas/impl/Subiterator.java
uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsTest.java
uimaj-parent/pom.xml

[UIMA-6342] Moving iterator beyond bounds does not invalidate it

---

pom.xml
uimaj-ep-cas-editor-ide/pom.xml
uimaj-ep-cas-editor/pom.xml
uimaj-ep-configurator/pom.xml
uimaj-ep-debug/pom.xml
uimaj-ep-jcasgen/pom.xml
uimaj-ep-launcher/pom.xml
uimaj-ep-pear-packager/pom.xml
uimaj-parent/pom.xml

- Switch to p2 resolver (backport of changes from main branch)

[UIMA-6341] Try out p2-layout-resolver

---

uima-docbook-overview-and-setup/src/docbook/conceptual_overview.xml

Noticed this spelling error while going through the documentation.

Corrected a spelling error

---

uimaj-json/src/main/java/org/apache/uima/json/JsonCasSerializer.java
uimaj-json/src/main/java/org/apache/uima/json/JsonMetaDataSerializer.java
uimaj-json/src/main/java/org/apache/uima/json/impl/JsonContentHandlerJacksonWrapper.java
uimaj-json/src/main/java/org/apache/uima/json/impl/MetaDataObjectSerializer_json.java
uimaj-json/src/test/java/org/apache/uima/json/JsonCasSerializerTest.java
uimaj-json/src/test/java/org/apache/uima/json/JsonMetaDataObjectTest.java
uimaj-json/src/test/java/org/apache/uima/json/JsonXmiCasSerializerTest.java
uimaj-json/src/test/java/org/apache/uima/resource/metadata/impl/TestFruitBagObject.java
uimaj-json/src/test/java/org/apache/uima/resource/metadata/impl/TestFruitObject.java

[UIMA-6373] Format UIMA Core Java SDK codebase

---

uimaj-core/src/test/java/org/apache/uima/cas/impl/BinaryCasSerDesPerformance.java
uimaj-core/src/test/java/org/apache/uima/internal/util/MultiThreadUtils.java
uimaj-core/src/test/java/org/apache/uima/internal/util/MultiThreadUtilsTest.java

- Upgrade two additional test classes which had slipped through in the last refactoring iteration

[UIMA-6372] Upgrade from JUnit 3 to JUnit 4 to JUnit 5

---

uimaj-core/src/test/java/org/apache/uima/cas/serdes/TestType.java
uimaj-core/src/test/java/org/apache/uima/cas/serdes/datasuites/MultiFeatureRandomCasDataSuite.java
uimaj-core/src/test/java/org/apache/uima/cas/serdes/datasuites/MultiTypeRandomCasDataSuite.java
uimaj-core/src/test/java/org/apache/uima/cas/serdes/generators/CasConfiguration.java
uimaj-core/src/test/java/org/apache/uima/cas/serdes/generators/MultiTypeRandomCasGenerator.java
uimaj-core/src/test/java/org/apache/uima/cas/serdes/scenario/SerDesTestScenario.java
uimaj-core/src/test/java/org/apache/uima/cas/serdes/transitions/CasSourceTargetConfiguration.java

- Added additional test type "SER_DES"
- Added option to configure random seed and to report random seed when randomized test fails
- When comparing CASes with toComparableString, first convert both CASes to the string representation and then compare the string representation

[UIMA-6374] Create CAS (de)serialization test suite

---

uima-docbook-overview-and-setup/src/docbook/eclipse_setup.xml

Fixes the update site for uima v3 eclipse plugins.

Fixed v3 update site url

---

uimaj-core/src/main/java/org/apache/uima/cas/impl/FSClassRegistry.java
uimaj-core/src/main/java/org/apache/uima/internal/util/UIMAClassLoader.java
uimaj-core/src/test/java/org/apache/uima/cas/impl/FSClassRegistryTest.java

- Unregister UIMAClassLoader form the FSClassRegistry when close() is called

[UIMA-6413] Memory leak in FSClassRegistry

---

uimaj-core/src/main/java/org/apache/uima/internal/util/rb_trees/CompIntArrayRBT.java
uimaj-core/src/main/java/org/apache/uima/internal/util/rb_trees/IntArrayRBT.java
uimaj-core/src/test/java/org/apache/uima/internal/util/rb_trees/IntArrayRBTTest.java

[UIMA-6415] Deprecate unused IntArrayRBT and CompIntArrayRBT

---

uima-docbook-references/src/docbook/ref.xml.component_descriptor.xml

[UIMA-6418] Support additional parameters value types

---

uimaj-core/src/main/java/org/apache/uima/cas/CASRuntimeException.java
uimaj-core/src/main/java/org/apache/uima/cas/impl/SelectFSs_impl.java
uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsTest.java

- Added exceptions and tests to check the exceptions are really thrown

[UIMA-6423] Selecting a non-existing type returns all types

---

PearPackagingMavenPlugin/pom.xml

https://issues.apache.org/jira/browse/UIMA-6430

UIMA-6430 upgrade commons-io due to cve

---

uimaj-core/src/main/java/org/apache/uima/analysis_component/CasProcessor.java
uimaj-core/src/main/java/org/apache/uima/analysis_component/CasProcessorAnnotator.java
uimaj-core/src/main/java/org/apache/uima/analysis_component/JCasAnnotator_ImplBase.java
uimaj-core/src/main/java/org/apache/uima/analysis_component/JCasProcessor.java
uimaj-core/src/main/java/org/apache/uima/analysis_component/JCasProcessorAnnotator.java
uimaj-core/src/main/java/org/apache/uima/analysis_engine/impl/AnalysisEngineProcessorAdapter.java
uimaj-core/src/main/java/org/apache/uima/analysis_engine/impl/AnalysisEngineProcessorStub.java
uimaj-core/src/main/java/org/apache/uima/resource/ResourceServiceStub.java
uimaj-core/src/test/java/org/apache/uima/analysis_component/CasProcessorAnnotatorTest.java
uimaj-core/src/test/java/org/apache/uima/analysis_component/JCasProcessorAnnotatorTest.java

- Add default implementatins to AnalysisEngineServiceStub and ResourceServiceStub to reduce verbosity
- Add analysis engine implementations using CAS- or JCas-accepting methods
- Added tests

[UIMA-6431] Use lambda functions as CAS processors

---

pom.xml

- Exclude template files from RAT check
* Check that RAT does not fail the build

[UIMA-6433] Update issue and PR templates

---

uimaj-examples/src/main/eclipseProject/classpath
uimaj-examples/src/main/run_configuration/UIMA CAS Visual Debugger.launch
uimaj-examples/src/main/run_configuration/UIMA Document Analyzer.launch
uimaj-examples/src/main/run_configuration/UIMA JCasGen.launch
uimaj-examples/src/main/run_configuration/UIMA PEAR Installer.launch
uimaj-examples/src/main/run_configuration/UIMA Run AE.launch
uimaj-examples/src/main/run_configuration/UIMA Run CPE.launch
uimaj-examples/src/main/run_configuration/UIMA Run V3 migrate JCas from classes roots.launch
uimaj-examples/src/main/run_configuration/UIMA Run V3 migrate JCas from sources roots.launch
uimaj-examples/src/main/run_configuration/UIMA Start VNS.launch
uimaj-examples/src/main/run_configuration/UIMA Start Vinci Service.launch

- Removed m2e-related lines form the launch configurations
* Try running the "UIMA Document Analyzer" and others from Eclipse via their example launch configurations

[UIMA-6434] Some launch configs do not work

---

uimaj-parent/pom.xml

**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6454
- Apache UIMA Parent POM 14 -> 15-SNAPSHOT
* Check if the SHA512 hashes are generated properly (cf. https://issues.apache.org/jira/browse/UIMA-6453)

[UIMA-6454] Update dependencies (UIMA Java SDK 3.3.1)

---

uimaj-parent/pom.xml

**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6463
- Add toolchain plugin

[UIMA-6463] Use toolchains to ensure compatibility with Java 1.8

---

PearPackagingMavenPlugin/pom.xml
jcasgen-maven-plugin/pom.xml

- Removed the version override

Issue #230: Remove version overrides in Maven plugin modules

---

uimaj-core/pom.xml

- SPI resolution should be optional
* Ruta build will fail without this - try it :)

Issue #225: Improve deployment in OSGi environments

---

pom.xml
uimaj-legacy-jira-report/pom.xml
uimaj-parent/pom.xml

- Switch the configuration for the issues report in the main POM from Jira to GitHub and set GitHub as the new main issue management system
- Add a non-deployed module to also generate a report from issues that we still have on Jira
* Run build with `-Papache-release` and check that both reports are generated in the `issuesFixed` folder

Issue #260: Issues-fixed report for GitHub and Jira

---

uimaj-parent/pom.xml

- log4j 2.17.1 -> 2.19.0
- junit 5.8.2 -> 5.9.1 (not bundled, no license/notice update required)
- assertj 3.22.0 -> 3.23.1 (not bundled, no license/notice update required)

#270 - Update dependencies

---

uimaj-core/src/main/java/org/apache/uima/cas/impl/SelectFSs_impl.java
uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsFSArrayTest.java
uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsFSListTest.java

- Added a few simple tests for select on FSArray and FSList
- Fixed a bug in FSArray preventing the use of select

Issue #272: select on FSArray seems broken

---

pom.xml

- Move staging-related configurations into the auto-staging profile
* Run a test release without auto-staging

Issue #265: Unable to release without auto-staging

---

uimaj-parent/pom.xml

- parent-pom 16-SNAPSHOT -> 16

Issue #270: Update dependencies (3.4.0)

---

.asf.yaml

Protect main again (actually main-v2)

No issue: Protect main again (actually main-v2)

---

src/main/assembly/bin.xml
src/main/assembly/src.xml
uimaj-parent/pom.xml

- Use our own src.xml assembly descriptor again because we need to fine-tune a few things

Issue #300: Differences between source ZIP and repository tag

---

uimaj-ep-runtime/pom.xml

- Added missing package export
* Build UIMA update site and install plugins into Eclipse
* Build UIMA Ruta update site and install plugins into Eclipse
* See if it works

Issue #306: Cannot install Ruta 3.3.0 workbench against UIMA 3.4.0 Eclipse plugins

---

uimaj-parent/pom.xml

- p2-layout-resolver 1.5.0 -> 1.7.0
* Np specific test procedure
* p2-layout-resolver is a build-only dependencies, no update of NOTICE/LICENSE files required

Issue #302: Update dependencies

---

uimaj-core/src/main/java/org/apache/uima/internal/util/Class_TCCL.java

- Consider TCCL when looking for class
- Improved exception where we hook up the suppressed exceptions from all the classloaders that failed and where the error message includes the classloaders as well
- Deprecated two methods that are no longer used or should no longer be used because they would only take a single classloader into account instead of trying multiple

Issue #315: ThreadContextClassLoader ignored by ResourceManager when extension classloader is set

---

PearPackagingMavenPlugin/pom.xml
pom.xml
uima-doc-v3-maintainers-guide/pom.xml
uima-doc-v3-users-guide/pom.xml
uimaj-core/pom.xml
uimaj-parent/pom.xml

- commons-io 2.11.0 -> 2.13.0
- commons-csv 1.8 -> 1.10.0
- asciidoctor-maven-plugin 2.1.0 -> 2.2.4
- asciidoctor 2.4.2 -> 2.5.8
- asciidoctor-pdf 1.5.4 -> 2.3.7
- log4j 2.19.0 -> 2.20.0
- jackson 2.13.1 -> 2.15.2
- junit 5.9.1 -> 5.9.3
- xmlunit 2.9.0 -> 2.9.1
- assertj 3.23.1 -> 3.24.2

Issue #317 - Update dependencies

---

uimaj-core/src/main/java/org/apache/uima/cas/impl/SelectFSs_impl.java

Issue #319: SelectFSs_impl.close() creates stream just to close it

---

jcasgen-maven-plugin/src/it/classpath/pom.xml
jcasgen-maven-plugin/src/it/m2e/pom.xml
jcasgen-maven-plugin/src/it/multimodule/crossref1/pom.xml
jcasgen-maven-plugin/src/it/multimodule/crossref2/pom.xml
jcasgen-maven-plugin/src/it/simple/pom.xml
uimaj-parent/pom.xml

* UIMA Parent POM 16 -> 17-SNAPSHOT (for Tycho 4.0.0)
* Updates Tycho as a build dependency - no need to update NOTICE files

Issue #325: Update dependencies

---

aggregate-uimaj/pom.xml
pom.xml
uimaj-bom/pom.xml

- BOM should not inherit from UIMAJ parent pom which does the internal dependency management

Issue #327: Provide a BOM

---

Jenkinsfile
uimaj-eclipse-feature-runtime/pom.xml
uimaj-eclipse-feature-tools/pom.xml

- Disable quality checking plugins on Jenkins to speed up the build
- Try fixing the checksum files for the Eclipse features
* Check if the generated checksum files that end up in the repository contain the proper filenames
* Try building Ruta...

Issue #341: Deploy Eclipse feature definitions to Maven repo

---

uimaj-core/src/main/java/org/apache/uima/cas/impl/TypeSystemUtils.java
uimaj-core/src/main/java/org/apache/uima/util/TypeSystemUtil.java

- Moved the two methods to the public TypeSystemUtil class
- Deprecate them in the old place and mark them for removal in next major version

Issue #369: Move isTypeName and isFeatureName to public API

---

uimaj-core/src/main/java/org/apache/uima/analysis_engine/impl/TaeDescription_impl.java
uimaj-core/src/main/java/org/apache/uima/cas/impl/BooleanConstraint.java
uimaj-core/src/main/java/org/apache/uima/cas/impl/FSBooleanConstraintImpl.java
uimaj-core/src/main/java/org/apache/uima/cas/impl/PathConstraint.java
uimaj-core/src/main/java/org/apache/uima/flow/impl/AnalysisSequenceCapabilityNode.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/AllowedValue_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/Capability_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/ConfigurationGroup_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/ConfigurationParameterDeclarations_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/ConfigurationParameterSettings_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/ConfigurationParameter_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/FeatureDescription_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/FsIndexDescription_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/FsIndexKeyDescription_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/NameValuePair_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/ResourceMetaData_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/SimplePrecondition_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/TypeDescription_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/TypePriorities_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/TypePriorityList_impl.java
uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/TypeSystemDescription_impl.java
uimaj-core/src/test/java/org/apache/uima/cas/impl/SerDesTstCommon.java
uimaj-core/src/test/java/org/apache/uima/impl/UimaContext_implTest.java
uimaj-core/src/test/java/org/apache/uima/resource/ConfigurableResource_implTest.java
uimaj-core/src/test/java/org/apache/uima/resource/metadata/impl/TestFruitBagObject.java
uimaj-json/src/test/java/org/apache/uima/resource/metadata/impl/TestFruitBagObject.java
uimaj-tools/src/main/java/org/apache/uima/tools/cvd/AutoFoldingMenu.java

- Added missing serialVersionUID
- Made serialVersionUID private

Issue #374: serialVersionUID should be present and private

---

uimaj-core/src/main/java/org/apache/uima/cas/impl/SelectFSs_impl.java
uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsTest.java

- If no index is available, fall back to the altSourceIterator or the fsIterator
- Added test

Issue #368: select(AnnotationBaseFs-type).count() seems to return MAX_LONG

---

PearPackagingMavenPlugin/src/main/java/org/apache/uima/pear/tools/PearPackagingMojo.java
jcasgen-maven-plugin/src/main/java/org/apache/uima/tools/jcasgen/maven/JCasGenMojo.java

- Mark the plugins as thread-safe

Issue #398: Mark Maven plugins as thread-safe

---

uimaj-core/src/main/java/org/apache/uima/spi/TypeSystemProvider_ImplBase.java

- Require specifying extension when initializing TypeSystemProvider_ImplBase

Issue #385: Allow import of type systems published through SPI

---

uimaj-parent/pom.xml

Issue #404: Remove toolchains

---

pom.xml
uimafit-maven-plugin/pom.xml
uimaj-core/src/test/java/org/apache/uima/resource/impl/PearSpecifier_implTest.java
uimaj-parent/pom.xml

- asciidoctor: 2.5.10 → 3.0.0
- asciidoctor.pdf: 2.3.9 → 2.3.19
- assertj: 3.24.2 → 3.26.3
- bytebuddy: → 1.15.10
- commons-csv: 1.10.0 → 1.12.0
- commons-io: 2.15.0 → 2.17.0
- commons-lang3: 3.13.0 → 3.17.0
- guava: 11.0.1 → 11.0.2
- jackson: 2.15.2 → 2.18.1
- junit: 5.10.1 → 5.11.3
- junit-platform: 1.10.1 → 1.11.3
- log4j: 2.20.0 → 2.24.1
- mockito: 5.7.0 → 5.14.2
- spring: 5.3.30 → 5.3.39
- xmlunit: 2.9.1 → 2.10.0
<sub><sup>Only dependencies under [approved licenses](http://www.apache.org/legal/resolved.html#category-a) are allowed. LICENSE and NOTICE files in the respective modules where dependencies have been added as well as in the project root have …

Issue #409: Update dependencies

---

pom.xml
src/main/assembly/bin-without-jackson.xml
src/main/assembly/bin.xml
src/main/bin_distr_license_notices/LICENSE.txt
src/main/bin_distr_license_notices/NOTICE-without-jackson.md
src/main/bin_distr_license_notices/NOTICE.md
uimaj-parent/pom.xml

- Include uimaFIT and dependencies in the binary distribution
- Update NOTICE and LICENSE files that are included in the binary distribution to include those of the new JARs in the binary distribution

Issue #393: Include uimaFIT artifacts in binary distribution
