apache/uima-uimaj

- uimaj-core/src/test/java/org/apache/uima/cas/impl/ConcurrentBinarySerializationTest.java
- TUnit test which triggers the concurrent serialization data corruption situation
> [UIMA-6162] Concurrent binary serialization produces corrupt output

- uimaj-core/src/main/java/org/apache/uima/cas/SelectFSs.java
- uimaj-core/src/main/java/org/apache/uima/cas/impl/SelectFSs_impl.java
- uimaj-cpe/.gitignore
- uimaj-parent/pom.xml
Adds additional signatures to support using FeatureStructure (interface), a super of AnnotationFS, in selectFS methods, without disturbing existing methods, and thus preserving binary compatibility.
Also, the existing methods (using TOP) have less run-time "casting" which might be a very minor performance boost (not measured).
> Uima 6159 select fs allow annotation fs in addition to top

- uimaj-core/pom.xml
- uimaj-core/src/main/java/org/apache/uima/cas/text/AnnotationFS.java
- uimaj-core/src/main/java/org/apache/uima/jcas/tcas/Annotation.java
- uimaj-core/src/main/java/org/apache/uima/util/CasCreationUtils.java
- uimaj-core/src/test/java/org/apache/uima/jcas/tcas/AnnotationTest.java
- uimaj-parent/pom.xml
Jira: https://issues.apache.org/jira/browse/UIMA-6152
- Introduce a Unicode-aware trim() method on AnnotationFS
- Added unit tests
- Added CasCreationUtils.createCas() no-args convenience method
- Added new dependency on assertj + dependency management for it
> [UIMA-6152] "trim" method for AnnotationFS

- uimaj-v3migration-jcas/src/main/java/org/apache/uima/migratev3/jcas/MigrateJCas.java
- Add explicit cast of null to ClassLoader to resolve ambiguity
Jira: https://issues.apache.org/jira/browse/UIMA-6170
> [UIMA-6170] Ambiguous method call when compiling on Java 13

- .gitignore
- uimaj-parent/pom.xml
- Remove profiles which are already declared in UIMA parent POM from this one
- Remove unnecessarily declared properties
- Define japcmp.postAnalysisScript property as required by UIMA parent POM enforce-compatibility profile
- Add issuesFixed folder to .gitignore
- Upgrade to UIMA parent POM 14-SNAPSHOT
Jira: https://issues.apache.org/jira/browse/UIMA-6184
> [UIMA-6184] Move code quality profiles to parent POM

- uimaj-core/src/main/java/org/apache/uima/pear/util/XMLUtil.java
- uimaj-core/src/test/java/org/apache/uima/pear/util/TestPearInstallationVerification.java
- Escape XML element values in XMLUtil (which is used to serialize PEAR installation descriptors
- Added unit test trying to install PEAR into a path with an XML special character
- Cleaned up and modernized TestPearInstallationVerification
- Formatted XMLUtil (basically adding missing curlies)
JIRA: https://issues.apache.org/jira/browse/UIMA-6225
> [UIMA-6225] Unable to install a pear package into a directory containing special character like <,> or &

- .gitignore
- uimaj-parent/pom.xml
Reverts changes made towards upgrading UIMAJ Core to the UIMA Parent POM 14 (unreleased as of yet).
The changes will be re-added in a separate branch to be merged after the parent POM 14 has actually been released. This avoids having a SNAPSHOT dependency in UIMAJ Core master.
> Revert uima 6184

- uimaj-core/src/main/java/org/apache/uima/cas/impl/CASImpl.java
- uimaj-core/src/main/java/org/apache/uima/cas/impl/FSsTobeAddedback.java
- uimaj-core/src/test/java/org/apache/uima/pear/util/TestPearInstallationVerification.java
- Restore dropping protection levels in the CAS when closing a FSsTobeAddedback context
@mischor Unfortunately, I can't provide a unit test because I only have a hunch in which situation this happens exactly. The piece of code I encountered problems in is pretty complex and a unit test is not easy to extract. Maybe you have a good idea for constructing a proper unit test once you see this fix.
**Jira link:** https://issues.apache.org/jira/browse/UIMA-6168
> [UIMA-6168] protect indexes fails when there were no indexed fs that needed protecting

- uimaj-tools/src/main/java/org/apache/uima/tools/cvd/FSNode.java
A general fix for this, explicitly pass in array length to makeNodes
> UIMA 6245 Fix CVD makeNodes to use array length

- Jenkinsfile
- uimaj-ep-cas-editor-ide/pom.xml
- uimaj-ep-cas-editor/pom.xml
- uimaj-ep-configurator/pom.xml
- uimaj-ep-configurator/src/main/java/org/apache/uima/taeconfigurator/editors/xml/NonRuleBasedDamagerRepairer.java
- uimaj-ep-debug/pom.xml
- uimaj-ep-launcher/pom.xml
- uimaj-ep-pear-packager/pom.xml
- Add exclusions for the artifacts that are missing
> [UIMA-6267] UIMA SDK Eclipse Plugins fail to build after Eclipse 2020-09 release

- uimaj-core/src/main/java/org/apache/uima/cas/impl/Subiterator.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsTest.java
> [UIMA-6269] select.coveredBy with includeAnnotationsWithEndBeyondBounds has broken edge case

- uimaj-core/src/main/java/org/apache/uima/internal/util/EncodedPrintStream.java
- Make EncodedPrintStream.writeBytes(byte[]) public like the super method
> [UIMA-6272] UIMA doesn't build on Java 14

- uimaj-cpe/src/main/java/org/apache/uima/collection/impl/cpm/BaseCPMImpl.java
- uimaj-parent/pom.xml
Fix JavaDoc and exclude .factorypath Eclipse configuration file from rat check
> [NO JIRA] Fix JavaDoc and exclude .factorypath Eclipse configuration file from rat check

- uimaj-core/src/main/java/org/apache/uima/cas/impl/SelectFSs_impl.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsTest.java
- Use true offsets of the reference annotation to determine starting point of the iterator
- Added unit tests for following and preceeding with and without skipping
> UIMA-6284: select.following() fails to find adjacent annotations

- uimaj-core/src/main/java/org/apache/uima/cas/impl/SelectFSs_impl.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsTest.java
- Added extra condition that skips annotations which are at the same location as the reference location when doing a "following" selection
- Added additional unit tests
> [UIMA-6285] select.following() on a zero-width annotation returns other zero-width annotation at same location

- uimaj-core/src/main/java/org/apache/uima/cas/SelectFSs.java
- uimaj-core/src/main/java/org/apache/uima/cas/impl/SelectFSs_impl.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsTest.java
- When selecting following annotations, skip over zero-width annotations that are the the end position of the reference interval
- Added unit test checking behavior for zero-width annotations at start/end of reference when selecting following and preceding
> [UIMA-6286] select following finds zero-width annotation at reference end position

- uimaj-core/src/main/java/org/apache/uima/jcas/cas/FSArray.java
- uimaj-core/src/test/java/org/apache/uima/cas/test/JCasClassLoaderTest.java
- Added unit test for the issue that the spliterator is returning the wrong type
- Added unit test for the issue that the toArray is returning the wrong type
- Refactored other JCas classloading tests a bit in the process
- Fixed the spliterator and toArray methods
> [UIMA-6287] FSArray.spliterator fails to handle pear case

- uimaj-core/src/main/java/org/apache/uima/cas/impl/Subiterator.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsAssert.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsCoveredByWithTypePrioritiesTest.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsTest.java
- Fixed issue that relevant annotations might be skipped if they occur before the boundary annotation in the index
- Fixed issue that the boundary annotation might be in the result list although it shouldn't be included
- Fixed issue that an unchecked bounds check may trigger a NoSuchElementException because the iterator has become invalid
- Added several test cases derived from the case provided with the original issue report - in particular without using any of uimaFIT
> [UIMA-6289] SelectFS.coveredBy not selecting annotations with exact same bounds as annotation argument

- uimaj-parent/pom.xml
- This repo no longer exists and checking it just makes the build turn longer
> [NO JIRA] Remove Eclipse Maven Repo

- uimaj-parent/pom.xml
- Remove profiles which are already declared in UIMA parent POM from this one
- Remove unnecessarily declared properties
- Define japcmp.postAnalysisScript property as required by UIMA parent POM enforce-compatibility profile
- Upgrade to UIMA parent POM 14-SNAPSHOT
**To be merged only after the UIMA Parent PO 14 has been released - mind updating the parent POM reference in the PR before merging.**
**Jira link:** https://issues.apache.org/jira/browse/UIMA-6234
> [UIMA-6234] Upgrade to UIMA Parent POM 14 (main-v2)

- uimaj-core/src/main/java/org/apache/uima/resource/PearSpecifier.java
- uimaj-core/src/main/java/org/apache/uima/resource/impl/PearSpecifier_impl.java
- Ensure to return a non-null value even if the internal field is null.
> [UIMA-6313] PearSpecifier_impl methods return null despite promise not to do so

- uimaj-core/src/test/java/org/apache/uima/cas/test/JCasClassLoaderTest.java
- Backport the extended JCasClassLoader unit tests from UIMAv3
- So with the fix actually all the JCasClassLoaderTest tests that run in UIMAv3 (all of them) also run in UIMAv2.
> [UIMA-6310] JCasClassLoaderTest sometimes fails

- uimaj-core/src/main/java/org/apache/uima/cas/impl/BinaryCasSerDes6.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/CasTypeSystemMapperTest.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/OrderedFsSet_array_Test.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsNoJCasTest.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/SerDesForm4Test.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/SerDesForm6ExtraTest.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/SerDesForm6Test.java
- uimaj-core/src/test/java/org/apache/uima/cas/test/GrowingTheCasNoJcasCacheTest.java
- uimaj-core/src/test/java/org/apache/uima/cas/test/IteratorSortedTest.java
- uimaj-core/src/test/java/org/apache/uima/internal/util/rb_trees/Int2IntRBTTest.java
- uimaj-core/src/test/java/org/apache/uima/internal/util/rb_trees/IntArrayRBTTest.java
- uimaj-core/src/test/java/org/apache/uima/pear/util/PearInstallationVerificationTest.java
- uimaj-core/src/test/java/org/apache/uima/util/impl/Log4jLogger_implTest.java
- Rename tests so that Maven actually finds and executes them
> UIMA-6318: Deserialization of array subtypes fails (form6)

- Jenkinsfile
- pom.xml
- uimaj-cpe/pom.xml
- uimaj-ep-cas-editor-ide/pom.xml
- uimaj-ep-cas-editor/pom.xml
- uimaj-examples/pom.xml
- uimaj-json/pom.xml
- uimaj-parent/pom.xml
- Clean up rat configuration
- Enable rat on Jenkins builds
- Exclude PEAR file used during testing from rat check
- Remove rat excludes which are already included in the parent POM
> [UIMA-6322] Clean up rat configuration v2

- uima-doc-v3-users-guide/src/docs/asciidoc/uv3.migration.aids.adoc
- uimaj-core/src/main/java/org/apache/uima/cas/impl/CASImpl.java
- uimaj-core/src/main/java/org/apache/uima/cas/impl/FsIndex_bag.java
- uimaj-core/src/main/java/org/apache/uima/cas/impl/FsIndex_set_sorted.java
- uimaj-core/src/main/java/org/apache/uima/cas/impl/FsIndex_singletype.java
- uimaj-core/src/main/java/org/apache/uima/cas/impl/TypeSystemImpl.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/FSIndexTest.java
- Perform the check if a type matches the expected type system not only in FsIndex_set_sorted.deleteFS but also in other deleteFS and insert methods
- Extract the check into a separate method
- Also perform the check when creating a feature structure via the CAS
- Added and documented option to disable strict checking
> [UIMA-6348] Race-condition in TypeSystemImpl commit

- uimaj-parent/pom.xml
- Upgrade japicmp / groovy to be compatible with Java 16
- Also bump p2-layout-resolver to be compatible with Java 16
(cherry picked from commit a60114e837f445db8bacc5049be9f46259b53eb6)
> UIMA-6349: japicmp post processing script fails with Java 16

- uimaj-core/pom.xml
- uimaj-core/src/main/java/org/apache/uima/cas/impl/BinaryCasSerDes.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/FSIndexTest.java
- uimaj-core/src/test/java/org/apache/uima/cas/test/CompleteSerializationTest.java
- Fixed issue by calling setupCasFromCasMgrSerializer in reinit(CASCompleteSerializer) instead of using incomplete custom code
- More thorough cleaning up in setupCasFromCasMgrSerializer()
- Adjusted FSIndexTest so it runs also when "uima.enable_strict_type_source_check" is enabled
- Enable "uima.enable_strict_type_source_check" for Maven surefire builds
> [UIMA-6352] reinit(CASCompleteSerializer) does not properly reset indexes

- uimaj-core/src/main/java/org/apache/uima/util/impl/Logger_common_impl.java
- Pass arg2 down to the next method instead of discarding it
> [UIMA-6353] Logger_common_impl.error(String arg0, Object arg1, Object arg2) swallows last argument

- src/main/assembly/bin-without-jackson.xml
- src/main/assembly/bin.xml
- uima-doc-v3-users-guide/pom.xml
- uima-doc-v3-users-guide/src/docs/asciidoc/uv3.migration.aids.adoc
- Adjust assemblies to include the "doc-v3" instead of the "docbook-v3"
- Fix properties table
> [UIMA-6305] Convert UIMAv3 User's Guide from DocBook to Asciidoc

- uimaj-core/src/main/java/org/apache/uima/cas/impl/CASImpl.java
- uimaj-core/src/main/java/org/apache/uima/jcas/impl/JCasHashMapSubMap.java
- uimaj-core/src/test/java/org/apache/uima/cas/test/FSCreatedInPearContextTest.java
- fixed trampoline map
- added test that checks annotation instance in mocked pear context
> UIMA-6367: JCas cover annotation created in PEAR context replaced during index operations

- uima-docbook-overview-and-setup/src/docbook/conceptual_overview.xml
- uimaj-core/src/main/java/org/apache/uima/cas/impl/CASImpl.java
- uimaj-core/src/main/java/org/apache/uima/jcas/impl/JCasHashMapSubMap.java
- uimaj-core/src/test/java/org/apache/uima/cas/test/FSCreatedInPearContextTest.java
- fixed trampoline map
- added test that checks annotation instance in mocked pear context
- Add a debug message if CAS switchClassLoader is called with a non UimaClassLoader because the UimaClassLoader has special magic without which the FS generators may create JCas wrappers from the wrong classloader (i.e. not the swiched classloader but the app classloader)
> UIMA-6367 JCas cover annotation created in pear context replaced during index operations

- uimaj-core/src/main/java/org/apache/uima/cas/impl/CasSerializerSupport.java
- Check if a FS is an emtpty array and if so do not warn about multiple references because empty arrays are immuntable and multi-referncing them is a valid approach
> [UIMA-6377] Spurious multipleReferencesAllowed warning when serializing empty arrays

- uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_BINARY_TSI_Test.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_BINARY_Test.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_COMPRESSED_FILTERED_TSI_Test.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_SERIALIZED_TSI_Test.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_XCAS_Test.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_XMI_1_0_PRETTY_Test.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_XMI_1_1_PRETTY_Test.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasToComparableText.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/SerDesCasIOTestUtils.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/datasuites/CasDataSuite.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/datasuites/MultiFeatureRandomCasDataSuite.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/datasuites/MultiTypeRandomCasDataSuite.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/datasuites/ProgrammaticallyCreatedCasDataSuite.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/generators/MultiFeatureRandomCasGenerator.java
- Allow configuration of empty/null elements in StringArrayFS when the MultiFeatureRandomCasDataSuite is used
- Fixes XMI and XCAS tests against the MultiFeatureRandomCasDataSuite
- Improve stability of order of feature structures in CasToComparableText by introducing a non-recursive "featureHash"
> [UIMA-6374] Create CAS (de)serialization test suite

- uimaj-cpe/src/main/java/org/apache/uima/collection/impl/cpm/engine/CPMEngine.java
- uimaj-cpe/src/main/resources/org/apache/uima/collection/impl/cpm/cpm_messages.properties
- Factor ThreadGroupDestroyer out into a static inner class to avoid the reference on the CPMEngine
- Log a warning when a non-CPE thread is preventing the CPM thread group from shutting down
- Auto-formatting
> [UIMA-6401] CPE ThreadGroupDestroyer keeps unnecessary reference on CPMEngine

- uima-docbook-references/src/docbook/ref.xml.component_descriptor.xml
- uimaj-core/src/main/java/org/apache/uima/UimaContextHolder.java
- Use a weak reference for the context in the context holder by default so that threads that are inheriting the context holder don't prevent the context from being garbage collected
> [UIMA-6400] UimaContextHolder threadlocal can leak

- uimaj-core/src/main/java/org/apache/uima/internal/util/UIMAClassLoader.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/FSClassRegistryTest.java
- uimaj-core/src/test/java/org/apache/uima/resource/impl/ResourceManager_implTest.java
- Handle the circular dependency between the static initializer blocks of TypeSystemImpl and FSClassRegistry in UIMAClassLoader and in the FSClassRegistryTest
- Add another simple test that just creates a resource manager with an extension classpath and then destroys it again to ensure it does not generate an exception when trying to unregister the resource manager's UIMAClassLoader from the FSClassRegistry on destroy
> [UIMA-6413] Memory leak in FSClassRegistry

- uimaj-cpe/src/main/java/org/apache/uima/collection/impl/cpm/BaseCPMImpl.java
- uimaj-cpe/src/main/java/org/apache/uima/collection/impl/cpm/Checkpoint.java
- uimaj-cpe/src/main/java/org/apache/uima/collection/impl/cpm/engine/ArtifactProducer.java
- uimaj-cpe/src/main/java/org/apache/uima/collection/impl/cpm/engine/BoundedWorkQueue.java
- uimaj-cpe/src/main/java/org/apache/uima/collection/impl/cpm/engine/CPMEngine.java
- uimaj-cpe/src/main/java/org/apache/uima/collection/impl/cpm/engine/CPMExecutorService.java
- uimaj-cpe/src/main/java/org/apache/uima/collection/impl/cpm/engine/DebugControlThread.java
- uimaj-cpe/src/main/java/org/apache/uima/collection/impl/cpm/engine/ProcessingUnit.java
- uimaj-cpe/src/main/resources/org/apache/uima/collection/impl/cpm/cpm_messages.properties
- Refactor the CPMThreadGroup into a CPMExecutionService
- Replace Thread.join() calls with Future.get() calls
- Replace the ThreadGroupDestroyer thread a simple call to shutdown()
- Replace the uncaught exception handler with overriding ThreadPoolExecutor.afterExecute()
- Clean up and format few classes
> [UIMA-6412] Stop using ThreadGroup in CPMEngine

- uimaj-core/src/test/java/org/apache/uima/internal/util/rb_trees/IntArrayRBTTest.java
Remove an assert which could randomly fail depending on which numbers the RNG was interting into the RB tree and which was superseded by another assert anyway
> [NO JIRA] Fix randomly failing test

- uimaj-parent/pom.xml
- Enforce that releases are made with a Java 1.8
> [UIMA-6354] Limit permitted JDK to minimal JDK for release builds

- uimaj-core/src/main/java/org/apache/uima/cas/CAS.java
- uimaj-core/src/main/java/org/apache/uima/cas/FSIndex.java
- uimaj-core/src/main/java/org/apache/uima/cas/impl/SelectFSs_impl.java
- uimaj-core/src/main/java/org/apache/uima/jcas/JCas.java
- uimaj-core/src/main/java/org/apache/uima/jcas/cas/FSList.java
- uimaj-core/src/main/java/org/apache/uima/jcas/cas/SelectViaCopyToArray.java
- Check parameter value of type(xxx) selectors for a non-null parameter
- Added a anyType() selector to allow explicitly requesting any type (which is the default behavior anyway)
- Update JavaDoc
> [UIMA-6388] CAS.select(null) returns all annotations

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/refactoring.md
- .github/PULL_REQUEST_TEMPLATE.md
- Added PR template
- Added tentative issue templates in case we switch from Jira to GitHub Issues
- Added contact links to the "new issue" page in case we switch from Jira to GitHub Issues
> [UIMA-6433] Update issue and PR templates

- uimaj-examples/src/main/deploy/vinci/Deploy_MeetingDetectorTAE.xml
- uimaj-examples/src/main/deploy/vinci/Deploy_PersonTitleAnnotator.xml
- uimaj-examples/src/main/deploy/vinci/Deploy_XmiWriterWithTutorialTypeSystem.xml
- Use relative paths - relative to the example project so that the "Start Vinci service" launch config works
> [UIMA-6435] Vinci example descriptors do not work

- pom.xml
- uimaj-parent/pom.xml
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6440
- Add several plugins and executions to the apache-release profile in the top-level POM to auto-stage the release candidate during a release build
- Removed unused 'assemblyFinalName' property
* Initialize a local svn repo: `svnadmin create /my/local/testrepo`
* Do a test build: `mvn -Papache-release -DskipTests -Dmaven.deploy.skip -Dstaging-scm-root='scm:svn:file:///my/local/testrepo/' -Denforcer.skip clean install`
* Check if the commit made it in `svn log file:///my/local/testrepo/`
<sub><sup>Only dependencies under [approved licenses](http://www.apache.org/legal/resolved.html#category-a) are allowed. LICENSE and …
> [UIMA-6440] Stage release artifacts as part of the build

- uima-doc-v3-maintainers-guide/src/docs/asciidoc/uv3.release.adoc
- uimaj-parent/pom.xml
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6459
- UIMA Parent POM 15-SNAPSHOT -> 15
- Also includes minor change for UIMA-6436
> [UIMA-6459] Upgrade dependencies

- uimaj-core/src/main/java/org/apache/uima/pear/util/FileUtil.java
- uimaj-core/src/main/java/org/apache/uima/resource/impl/RelativePathResolver_impl.java
- uimaj-core/src/test/java/org/apache/uima/resource/impl/RelativePathResolver_implTest.java
- uimaj-core/src/test/java/org/apache/uima/util/FileUtilsTest.java
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6469
- Introduce various constants
- Use try-with-resources to more effect
- Modernize and extend tests
- More constants instead of magic strings
- Centralize normalization of paths to unix paths
- Improve JAR extraction handling
> [UIMA-6469] Cleaning up file handling code

- uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasToComparableText.java
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6473
- Add missing else
- Fix use of wrong variable in if statement
> [UIMA-6473] CasToComparableText is broken

- PearPackagingMavenPlugin/pom.xml
- jcasgen-maven-plugin/pom.xml
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6479
- Switch from maven-project 2.0.4 to maven-core 3.0.3 (which is also used in the jcasgen plugin)
- Also mark maven-core as provided in the jcasgen plugin
> [UIMA-6479] PearPackagingMavenPlugin has ancient JUnit dependency

- PearPackagingMavenPlugin/pom.xml
- jcasgen-maven-plugin/pom.xml
- uimaj-parent/pom.xml
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6454
- maven-plugin-api 3.1.0 -> 3.2.4
- maven-core 3.0.3 -> 3.2.4
- maven-toolchains-plugin -> 3.1.0 (build)
- change scope of Maven dependencies in Maven plugin modules to "provided"
> [UIMA-6454] Update dependencies (UIMA Java SDK 3.3.1)

- uimaj-core/src/test/java/org/apache/uima/cas/serdes/SerDesCasIOTestUtils.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/scenario/DesSerTestScenario.java
- Added `SerDesCasIOTestUtils.roundTripDesSerScenariosComparingFileContentsNormalizingNewlines`
> [#222] Support comparing test files irrespective of line endings

- uimaj-parent/pom.xml
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6454
- maven-plugin-plugin 3.6.1 -> 3.6.4
- japicmp-maven-plugin 0.15.3 -> 0.15.7
- inline eclipseP2RepoUrl property into repository declaration to avoid stressing out the resolver with variables
- groovy-jsr223 2.5.15 -> 2.5.17 (japicmp plugin dependency to support recent Java versions)
> [UIMA-6454] Update dependencies

- uimaj-core/src/main/java/org/apache/uima/cas/impl/BinaryCasSerDes6.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/SerDesForm6Test.java
- uimaj-core/src/test/java/org/apache/uima/util/CasIOUtilsTest.java
- Instead of only setting the default v2IdRef flag (which has no effect), set the flag on the CAS currently being processed
> #238 - Form 6 serializes non-reachable FSes but should not

- uimaj-core/src/main/java/org/apache/uima/cas/impl/CASImpl.java
- uimaj-core/src/main/java/org/apache/uima/cas/impl/SelectFSs_impl.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/SelectFsNoJCasTest.java
- Prevent helper annotation from getting an ID and being held onto even when holding onto FSes is enabled
> Issue #240: Helper annotation created by SelectFS should not survive

- uimaj-core/src/main/java/org/apache/uima/cas/CASRuntimeException.java
- uimaj-core/src/main/java/org/apache/uima/cas/impl/TypeSystemImpl.java
- uimaj-core/src/main/java/org/apache/uima/pear/util/FileUtil.java
- uimaj-core/src/main/resources/org/apache/uima/UIMAException_Messages.properties
- uimaj-core/src/test/java/org/apache/uima/jcas/test/JCasTest.java
- uimaj-core/src/test/java/org/apache/uima/pear/util/PearInstallationVerificationTest.java
- Add new message
- Use this message when an unregistered but defined type is being used
> Issue #235: Misleading error message when JCas type is not registered

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- uima-doc-v3-users-guide/src/docs/asciidoc/uv3.spi.adoc
- uima-doc-v3-users-guide/src/docs/asciidoc/version_3_users_guide.adoc
- uimaj-core/pom.xml
- uimaj-core/src/main/java/org/apache/uima/cas/impl/FSClassRegistry.java
- uimaj-core/src/main/java/org/apache/uima/spi/JCasClassProvider.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/FSClassRegistryTest.java
- uimaj-core/src/test/java/org/apache/uima/jcas/test/generatedx.xml
- uimaj-core/src/test/java/org/apache/uima/spi/JCasClassProviderForTesting.java
- uimaj-core/src/test/java/org/apache/uima/spi/SpiSentence.java
- uimaj-core/src/test/java/org/apache/uima/spi/SpiToken.java
- uimaj-core/src/test/resources/META-INF/services/org.apache.uima.spi.JCasClassProvider
- uimaj-ep-cas-editor-ide/.gitignore
- uimaj-ep-cas-editor/.gitignore
- uimaj-ep-configurator/.gitignore
- uimaj-ep-debug/.gitignore
- uimaj-ep-jcasgen/.gitignore
- uimaj-ep-launcher/.gitignore
- uimaj-ep-pear-packager/.gitignore
- uimaj-ep-runtime/.gitignore
- Added SPI for JCas classes
- Added test that FSClassRegistry is able to load JCas classes through the SPI
- Push exclusion of META-INF down into the bundle modules because we do not want to exclude the META-INF/services for SPI testing
> Issue #226: Provide SPI interfaces to locate descriptors

- uima-doc-v3-users-guide/src/docs/asciidoc/uv3.spi.adoc
- uimaj-core/src/main/java/org/apache/uima/util/TypeSystemUtil.java
> #245 - Utility method for loading type systems in SPI providers

- jVinci/.gitignore
- uimaj-adapter-vinci/.gitignore
- uimaj-core/.gitignore
- uimaj-core/src/main/java/org/apache/uima/resource/impl/RelativePathResolver_impl.java
- uimaj-cpe/.gitignore
- uimaj-tools/.gitignore
- Consider the TCCL in the RelativePathResolver_impl
> Issue #247 - RelativePathResolver should consider TCCL

- uimaj-core/src/main/java/org/apache/uima/cas/impl/FSClassRegistry.java
- When obtaining a MH for a lookup through a custom classloader, make sure it is a UIMAClassLoader because otherwise the MHLC magic cannot work and the JCas classes get loaded through the wrong classloader - in particular applies to SPIs in an OSGI environment
> Issue #226: Provide SPI interfaces to locate descriptors and JCas classes

- uimaj-cpe/pom.xml
- Turned uimaj-cpe into a fragment of uimaj-core because uimaj-core needs access to the packages of uimaj-cpe, e.g. because it accesses classes like CpeInclude via reflection in its factories
> Issue #225: Improve deployment in OSGi environments

- uimaj-core/src/main/java/org/apache/uima/internal/util/UIMAClassLoader.java
- If the class to be looked up is in the FsGenerator3 package, use the classloader of FsGenerator3
* No specific test scenario
> Issue #252: Potential failure to look up FsGenerator3 in OSGI-like contexts

- uimaj-core/src/main/java/org/apache/uima/impl/UIMAFramework_impl.java
- Wrap access with try-with-resources
> Issue #255: File handle leak accessing performanceTuning.properties

- uimaj-core/src/main/java/org/apache/uima/util/impl/Log4jLogger_impl.java
- Use reflection to pry-open a protected class that was previously public - frankly, this is not a good solution...
* Upgrade to log42 2.18.0 and build
* Upgrade to log42 2.18.0 and run with Java 17
> #267 - UIMA Log4jLogger_impl not compatible with log4j 2.18.0+

- uimaj-core/src/main/java/org/apache/uima/analysis_engine/impl/PrimitiveAnalysisEngine_impl.java
- Remove logging statement
* Build an AE that simply throws an exception in its process method
> Issue #268: UIMA components log and then re-throw exceptions which usually leads to errors being logged twice

- pom.xml
- uimaj-legacy-jira-report/pom.xml
- uimaj-parent/pom.xml
- Rename the marker file to trigger the issue report generation
- Add more configuration to the Jira report which is no longer set by the parent UIMA POM
- Make necessary changes to the GitHub issue report generation profile
* Run a test release
> Issue #283: Update issue report generation

- uimaj-core/src/main/java/org/apache/uima/cas/impl/CASImpl.java
- uimaj-core/src/test/java/org/apache/uima/cas/test/FSCreatedInPearContextTest.java
- If the id2base and id2tramp maps exist, only clear them, do not set them to null
> Issue #285: NPE while deserializing an XMI in a PEAR context

- uimaj-core/pom.xml
- uimaj-core/src/main/java/org/apache/uima/pear/util/FileUtil.java
- uimaj-core/src/main/java/org/apache/uima/util/impl/Constants.java
- uimaj-core/src/test/java/org/apache/uima/util/FileUtilsTest.java
This change introduces file-handling enhancements from apache/uima-uimaj#209 and apache/uima-uimaj#211 to the main-v2 branch, including the fix addressing CVE-2022-32287.
This meant porting the entire `org.apache.uima.util.impl.Constants` class and also the unit test with associated org.junit.jupiter libraries. Given that these are only used in the test scope, it didn't feel too outrageous to use them just in this test and keep the others how they've always been in v2.
* updated code for `org.apache.uima.pear.util.FileUtil` based on current code in main branch, including the method affected by CVE-2022-32287
* added `org.apache.uima.util.impl.Constants`, referenced from updated `FileUtil` code
* updated unit test `org.apache.uima.util.FileUtilTest`
* updated `pom.xml` …
> #289 - Porting file-handling enhancements from main branch

- uimaj-core/src/test/java/org/apache/uima/cas/serdes/CasSerializationDeserialization_XCAS_Test.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/SerDesCasIOTestUtils.java
- uimaj-core/src/test/java/org/apache/uima/cas/serdes/scenario/SerRefTestScenario.java
- run SerRef tests using a content comparison
> Issue #292: Make CAS serialization tests more robust

- PearPackagingMavenPlugin/pom.xml
- jVinci/pom.xml
- uimaj-adapter-vinci/pom.xml
- uimaj-core/pom.xml
- uimaj-cpe/pom.xml
- uimaj-document-annotation/pom.xml
- uimaj-ep-cas-editor-ide/pom.xml
- uimaj-ep-cas-editor/pom.xml
- uimaj-ep-configurator/pom.xml
- uimaj-ep-debug/pom.xml
- uimaj-ep-jcasgen/pom.xml
- uimaj-ep-launcher/pom.xml
- uimaj-ep-pear-packager/pom.xml
- uimaj-ep-runtime/pom.xml
- uimaj-examples/pom.xml
- uimaj-tools/pom.xml
- uimaj-v3migration-jcas/pom.xml
- Remove finalName override from the build section
* Check that the checksum files now contain the proper filename
* Run release build
* Check if Eclipse plugins can still be installed
* Check if examples are still there 
* Check that descriptors can still be opened using Eclipse plugins
* Check that at least one of the launch configs shipped with UIMA still works
> #298 - SHA512 checksums contain wrong file name

- uimaj-core/src/main/java/org/apache/uima/cas/impl/BinaryCasSerDes.java
- Skip all code related to reading the content of an array if the array is empty
- Formatting
> #304 - Unable to deserialize CAS if last element on the heap is an empty array

- uimaj-core/src/test/java/org/apache/uima/resource/metadata/impl/ImportResolverTest.java
- uimaj-core/src/test/java/org/apache/uima/resource/metadata/impl/TypeSystemDescription_implTest.java
- Try using deprecated non-escaping toURL() because it seems that  might be what the tested code is using internally as well
* Try running the test on Windows
> Issue #303: Build fails on Windows if namespace contains whitespace

- uimaj-core/pom.xml
- uimaj-core/src/main/java/org/apache/uima/cas/impl/FsIterator_set_sorted2.java
- uimaj-core/src/main/java/org/apache/uima/cas/impl/FsIterator_set_sorted_pear.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/FsIterator_set_sorted_pearTest.java
- uimaj-parent/pom.xml
- Fix issue in FsIterator_set_sorted_pear
* Adds Mockito as a test dependency. Mockito has MIT license. No need to update notice files since as a test dependency, we do not package it with releases.
> Issue #320: Copy of FsIterator_set_sorted_pear does not retain position

- jcasgen-maven-plugin/pom.xml
- jcasgen-maven-plugin/src/test/java/org/apache/uima/tools/jcasgen/maven/JCasGenMojoTest.java
- uimaj-adapter-vinci/pom.xml
- uimaj-component-test-util/pom.xml
- uimaj-core/pom.xml
- uimaj-ep-cas-editor-ide/pom.xml
- uimaj-ep-cas-editor/pom.xml
- uimaj-parent/pom.xml
- uimaj-test-util/pom.xml
- junit4 -> 4.13.2 (needed for Maven plugin test harness...)
- maven-plugin-testing-harness 2.0 -> 3.3.0
- maven-plugin-tools-javadoc 2.9 -> 3.5.2
- maven-compat -> 3.2.5
- junit5 5.9.3 -> 5.10.0
- asciidoctor 2.5.8 -> 2.5.10
- asciidoctor-pdf 2.3.7 -> 2.3.9
- Removed redundant plugin dependency override
- Depend on junit-jupiter-api instead of junit-jupiter-engine for unit tests
> Issue #325 - Update dependencies

- uimaj-ep-configurator/src/main/java/org/apache/uima/taeconfigurator/editors/MultiPageEditorContributor.java
- uimaj-ep-configurator/src/main/java/org/apache/uima/taeconfigurator/files/ContextForPartDialog.java
- Upgrade to IPreferenceStore and non-deprecated API (at least non-deprecated in the venerable Eclipse version we build against)
* Build Eclipse plugins
* Install into a vanilla Eclipse 20230-06
> Issue #337: Component description editor may not open in Eclipse

- uimaj-core/src/main/java/org/apache/uima/internal/util/UIMAClassLoader.java
- uimaj-core/src/main/java/org/apache/uima/resource/RelativePathResolver.java
- uimaj-core/src/main/java/org/apache/uima/resource/ResourceManager.java
- uimaj-core/src/main/java/org/apache/uima/resource/impl/ConfigurableDataResource_impl.java
- uimaj-core/src/main/java/org/apache/uima/resource/impl/DataResource_impl.java
- uimaj-core/src/main/java/org/apache/uima/resource/impl/RelativePathResolver_impl.java
- uimaj-core/src/main/java/org/apache/uima/resource/impl/ResourceManager_impl.java
- uimaj-core/src/main/java/org/apache/uima/resource/metadata/ResourceManagerConfiguration.java
- uimaj-core/src/main/java/org/apache/uima/util/impl/Settings_impl.java
- uimaj-core/src/test/java/org/apache/uima/resource/impl/RelativePathResolver_implTest.java
- Added methods to set the datapath using URLs
- Added support for URLs to the setDataPathElements(String...) method
- Deprecated methods that return the datapath in a way that is not URLs
- Added more unit tests
- Cleaning up code a bit
> #372 - Allow adding URLs to the datapath

- .asf.yaml
- Since we cannot configure the repo to allow merging without status checks for admins (because we are not project admins), I un-require the status checks to allow merging the bugfix branch into the release branch without having to set up a PR first.
* No specific test procecure
> No issue: Unrequire status checks

- .gitignore
- uimaj-core/src/main/java/org/apache/uima/cas/impl/FSClassRegistry.java
- uimaj-core/src/main/java/org/apache/uima/cas/impl/TypeSystemImpl.java
- uimaj-core/src/main/java/org/apache/uima/internal/util/UIMAClassLoader.java
- uimaj-core/src/test/java/org/apache/uima/cas/impl/TypeSystemImplTest.java
- uimaj-parent/pom.xml
- Added test case to check for the leak
- Changed code to always use the lookup from the classloader associated with the JCas wrapper class and deprecated methods (parameters) that passed though the lookup from elsewhere
- Changed to cache generators per JCas wrapper class to avoid one hidden classes being generated for the same generator repeatedly (since these are no longer garbage collected by current JREs)
<sub><sup>Only dependencies under [approved licenses](http://www.apache.org/legal/resolved.html#category-a) are allowed. LICENSE and NOTICE files in the respective modules where dependencies have been added as well as in the project root have been …
> Issue #371: Repeated creation of type systems can exhaust JVM metaspace

- uimaj-core/src/main/java/org/apache/uima/UIMAFramework.java
- uimaj-core/src/main/java/org/apache/uima/UimaContextAdmin.java
- uimaj-core/src/main/java/org/apache/uima/UimaContextAdminBuilder.java
- Added builder
- Added another factory method without any arguments for the simplest case
- Deprecated old factory method
- Deprecated three-args init method in UimaContextAdmin and added a replacement default method to the interface
* Use the builder
> Issue #387: Simplify creation of new UIMAContext

- uimaj-core/src/main/java/org/apache/uima/internal/util/UIMAClassLoader.java
- When trying to load a UIMA JCas class, fall back to using the UIMA framework classloader instead of the resource manager parent classloader which might not import all UIMA packages
* E.g. construct a situation where the parent classloader of a resource manager has no access to the UIMA JCas classes such as TOP.
> Issue #395: Potential failure to look up UIMA-internal classes in OSGI-like contexts

- uimafit-core/src/main/java/org/apache/uima/fit/factory/FsIndexFactory.java
- uimafit-core/src/main/java/org/apache/uima/fit/factory/TypePrioritiesFactory.java
- uimafit-core/src/main/java/org/apache/uima/fit/factory/TypeSystemDescriptionFactory.java
- uimaj-core/pom.xml
- uimaj-core/src/main/java/org/apache/uima/cas/impl/FSClassRegistry.java
- uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/ImportResolver.java
- uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/Import_impl.java
- uimaj-core/src/main/java/org/apache/uima/resource/metadata/impl/TypeSystemDescriptionImportResolverAdapter.java
- uimaj-core/src/main/java/org/apache/uima/spi/FsIndexCollectionProvider.java
- uimaj-core/src/main/java/org/apache/uima/spi/JCasClassProvider.java
- uimaj-core/src/main/java/org/apache/uima/spi/TypePrioritiesProvider.java
- uimaj-core/src/main/java/org/apache/uima/spi/TypeSystemDescriptionProvider.java
- uimaj-core/src/main/java/org/apache/uima/spi/TypeSystemProvider.java
- uimaj-core/src/main/java/org/apache/uima/spi/TypeSystemProvider_ImplBase.java
- uimaj-core/src/main/java/org/apache/uima/util/TypeSystemUtil.java
- uimaj-documentation/src/docs/asciidoc/fit/tools.uimafit.typesystem.adoc
- uimaj-documentation/src/docs/asciidoc/user/uv3.spi.adoc
- Enhance the Import_impl to look up descriptors via the type system description SPI
- Bit of cleaning up in related classes
> Issue #385: Allow import of type systems published through SPI

- .gitignore
- PearPackagingMavenPlugin/pom.xml
- aggregate-uimaj/pom.xml
- jcasgen-maven-plugin/pom.xml
- pom.xml
- uima-bnd-plugin/pom.xml
- uima-bnd-plugin/src/main/java/org/apache/uima/tools/bnd/UimaBndPlugin.java
- uimaj-bom/pom.xml
- uimaj-documentation/src/docs/asciidoc/tools.adoc
- uimaj-documentation/src/docs/asciidoc/tools/tools.bnd.adoc
- uimaj-parent/pom.xml
- Added uima-bnd-plugin
- Added documentation
* See documentation
> Issue #402: Provide bnd plugin to generate package imports based on imports in UIMA descriptors

- .gitattributes
- src/main/assembly/src.xml
- Exclude release profile marker files from release source ZIP
- Exclude release profile marker files from GitHub ZIP
* Try building from the source ZIP
> Issue #422: Exclude release-related marker files from source distributions

- uimaj-core/pom.xml
- uimaj-core/src/main/java/org/apache/uima/cas/SerialFormat.java
- uimaFIT will now use the UIMA Framework classloader to discover ValidationChecks, so the uimaj-core bundle needs to declare that SPI in its OSGi metadata
- Fix copy/paste issue in SerialFormat JavaDoc
> Issue #431: Issue using SPI-enabled type systems embedded into PEARs
